### ISSUE TITLE
Exception reported: Invalid index 0 (count: 0)

### ISSUE THREAD

**Issue by freakexeuLow** [GAMMACASE/NightVision#2]
Hey GAMMACASE,

I currently have the problem that NightVision reports this error (Sourcemod Version is 1.10 6494)

> L 09/17/2020 - 08:38:07: SourceMod error session started
> L 09/17/2020 - 08:38:07: Info (map "bhop_arcane_classic") (file "/home/user2-1/server/csgo/csgo/addons/sourcemod/logs/errors_20200917.log")
> L 09/17/2020 - 08:38:07: [SM] Exception reported: Invalid index 0 (count: 0)
> L 09/17/2020 - 08:38:07: [SM] Blaming: nightvision.smx
> L 09/17/2020 - 08:38:07: [SM] Call stack trace:
> L 09/17/2020 - 08:38:07: [SM]   [0] ArrayList.Get
> L 09/17/2020 - 08:38:07: [SM]   [1] Line 71, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\nightvision.sp::Settings::Empty
> L 09/17/2020 - 08:38:07: [SM]   [2] Line 156, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\nightvision.sp::OnClientDisconnect
> L 09/17/2020 - 08:38:07: Error log file session closed.

**Comment by GAMMACASE** [comment]
Can I see your ``addons/sourcemod/configs/nightvision.cfg`` file?

**Comment by freakexeuLow** [comment]
> 
> 
> Can I see your `addons/sourcemod/configs/nightvision.cfg` file?

of course [https://pastebin.com/M3VKBUj5](https://pastebin.com/M3VKBUj5)

**Comment by GAMMACASE** [comment]
This seems like a super rare case scenario, will change some stuff to fix this tho.

**Comment by freakexeuLow** [comment]
> This seems like a super rare case scenario, will change some stuff to fix this tho.

It is, have this problem also only on a few servers and thanks 👍🏼

**Comment by GAMMACASE** [comment]
Should be fixed now, reply here if it's not. Thanks for the report.
