### ISSUE TITLE
I suggest a new function

### ISSUE THREAD

**Issue by AKBricky** [GAMMACASE/NightVision#3]
On the other hand, I hope there's a function that way to make it darker

or

Using this function, it seems okay to make the map look dark

**Comment by GAMMACASE** [comment]
Not sure I fully understood what you mean, but you can create any color correction template you want, even the one that makes map darker (Read readme to see how to create one).

**Comment by GAMMACASE** [comment]
Closing this for now, lmk if that wasn't what you wanted.
